services:
  Subugoe\OaiBundle\Service\OaiService:
    alias: Subugoe\OaiBundle\Service\OaiServiceInterface

  Subugoe\OaiBundle\Service\OaiServiceInterface:
    class: Subugoe\OaiBundle\Service\OaiService
    arguments: ["@request_stack", "@solarium.client", "@oaitemp_filesystem", "@subugoe_iiif.translator", "%subugoe_oai%"]
    public: true

  Subugoe\OaiBundle\Controller\OaiController:
    autoconfigure: true
    autowire: true
