services:
  Subugoe\OaiBundle\Service\OaiService:
    alias: Subugoe\OaiBundle\Service\OaiServiceInterface

  Subugoe\OaiBundle\Service\OaiServiceInterface:
    class: Subugoe\OaiBundle\Service\OaiService
    autoconfigure: true
    autowire: true
    calls:
      - method: setRequestStack
        arguments:
          - '@request_stack'
      - method: setClient
        arguments:
          - '@solarium.client'
      - method: setOaiConfiguration
        arguments:
          - '%subugoe_oai%'


  Subugoe\OaiBundle\Controller\OaiController:
    autoconfigure: true
    autowire: true
